
task:
  name: "DumprX-1"
  only_if: $CIRRUS_REPO_OWNER == 'ajaysinghsati'
  skip: $CIRRUS_BRANCH == 'main'
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git
      - git config --global user.name "ajaysinghsati"
      - git config --global user.email "ajaysinghsati@gmail.com"
      - cd DumprX 
      - sudo bash setup.sh
      - ./dumper.sh https://gauss-componentotacostmanual-sg.allawnofs.com/remove-c7b3170d7bf82759c620704cf4d9a910/component-ota/22/12/22/d9fa21424242470c8880aa324b03b1f1.zip
      - git clone https://dumps.tadiphone.dev/dumps/oneplus/op535dl1.git
      
  
