
task:
  name: "Firmware Dump by DumprX"
  only_if: $CIRRUS_REPO_OWNER == 'ajaysinghsati'
  skip: $CIRRUS_BRANCH == 'main'
  
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      privileged: true
      cpu: 4
      memory: 16G

  Clone_script:
      - git clone --depth=1 --single-branch https://github.com/DumprX/DumprX.git
  
  
      

  Setup_script:
      - git config --global user.name "ajaysinghsati"
      - git config --global user.email "ajaysinghsati@gmail.com"
      - cd DumprX
      
      - sudo bash setup.sh

  DumprX_script:
      - cd DumprX || echo "Already in the Directory"
      - ./dumper.sh $(< ${CIRRUS_WORKING_DIR}/ROM_URL.txt)
      - cd out 
      - cd lineage-device-tree
      - git init 
      - git add .
      - git commit -m "first commit"
      - git branch -M main
      - git push https://phhgsi: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@github.com/phhgsi/lineage-device-tree.git
      

